#!/bin/bash
# /* vim: set filetype=sh ts=2 sw=2 sts=2 et : */

Me="Alfred W. Kerninghan"
Email="awk@att.com"

Awk=_var/awk
Tmp=_var/tmp
Docs=docs

if [ -f "./aok.rc" ]; then
  . ./aok.rc
fi

mkdir -p $Docs $Awk $Tmp

makeawk() {
  echo "# $1 to _awk/" 1>&2
  cat $1 | gawk '
  BEGIN {In = 1}
  gsub(/^"""/,"") {
    In =  1 - In
  }
  { print (In ? "" : "## ") gensub(/\.([a-zA-Z_])([a-zA-Z0-9_]*)/,
                                  "[\"\\1\\2\"]",
                                  "g") }
  '
}

makedoc() {
  echo "# $1 to docs/" 1>&2
  cat $1 | gawk '
  BEGIN {In = 1; Pre=1}
  gsub(/^"""/,"") {
    In =  1 - In
    if (Pre)
       Pre=0
    else {
      if (In)  {
        print ""
        print "```awk " $0
      } else {
        print "```" $0
        print ""
     }
    }
    next
  }
  Pre  { next }
      { sub(/^#/,"")
       print }
  END  { if (In) print "```\n" }
  '
}
vars() {
  if [ -f "$Tmp/awkvars.out" ]
  then
    egrep -v '[A-Z][A-Z]' $Tmp/awkvars.out |
    sed 's/^/W> rogue local: /'
  fi
}
profile() {
  cat $Tmp/awkprof.out
}

ready() {
  for auk1 in *.auk; do
  	awk1=$Awk/${auk1%.*}.awk
  	doc1=$Docs/${auk1%.*}.md
	  if [ "$auk1" -nt "$awk1" ]; then makeawk $auk1 > $awk1; fi
	  if [ "$auk1" -nt "$doc1" ]; then makedoc $auk1 > $doc1; fi
    git add  docs/*
  done
}

gitready() {
  git config --global user.email $Email
  git config --global user.name  $Me
  git config --global credential.helper cache
  git config credential.helper 'cache --timeout=3600'
}
old() {
  gitready
  git pull origin master
}
new() {
  gitready
  git add .
  git commit -am newStuff
  git push origin master
}
here() {
  cd $1; basename "$PWD";
}

ready

echo $1

if   [ "$1" == "new"     ]; then new;
elif [ "$1" == "old"     ]; then old;
elif [ "$1" == "profile" ]; then profile;
else
  AWKPATH="$Awk:$AWKPATH" gawk          \
       --dump-variables=$Tmp/awkvars.out \
       --profile=$Tmp/awkprof.out         \
       -f $1.awk
vars
fi 
