#!/bin/bash
# /* vim: set filetype=sh ts=2 sw=2 sts=2 et : */

MyName="Alfred Oliver Kerninghan"
MyEmail="awk@att.com"

Awk=_var/awk
Tmp=_var/tmp
Docs=docs

if [ -f "./aok.rc" ]; then . ./aok.rc; fi

mkdir -p $Docs $Awk $Tmp

makeawk() {
  echo "# $1 to _awk/" 1>&2
  cat $1 | gawk '
  BEGIN {In = 1}
  gsub(/^"""/,"") {
    In =  1 - In
  }
  { print (In ? "" : "## ") gensub(/\.([a-zA-Z_])([a-zA-Z0-9_]*)/,
                                  "[\"\\1\\2\"]",
                                  "g") }
  '
}

makedoc() {
  echo "# $1 to docs/" 1>&2
  cat $1 | gawk '
  BEGIN {In = 1; Pre=1}
  gsub(/^"""/,"") {
    In =  1 - In
    if (Pre)
       Pre=0
    else {
      if (In)  {
        print ""
        print "```awk " $0
      } else {
        print "```" $0
        print ""
     }
    }
    next
  }
  Pre  { next }
      { sub(/^#/,"")
       print }
  END  { if (In) print "```\n" }
  '
}
vars() {
  if [ -f "$Tmp/awkvars.out" ]
  then
    egrep -v '[A-Z][A-Z]' $Tmp/awkvars.out |
    sed 's/^/W> rogue local: /'
  fi
}
profile() {
  if [ -f "$Tmp/awkprof.out" ]; then
    cat $Tmp/awkprof.out
  fi
}

ready() {
  for aok1 in *.aok; do
  	awk1=$Awk/${aok1%.*}.awk
  	doc1=$Docs/${aok1%.*}.md
	if [ "$aok1" -nt "$awk1" ]; then makeawk $aok1 > $awk1; fi
	if [ "$aok1" -nt "$doc1" ]; then makedoc $aok1 > $doc1; fi
        git add $Docs
	git add $Docs/*
  done
}

gitready() {
  git config --global user.email $MyEmail
  git config --global user.name  $MyName
  git config --global credential.helper cache
  git config credential.helper 'cache --timeout=3600'
}
old() {
  gitready
  git pull origin master
}
new() {
  gitready
  git add .
  git commit -am newStuff
  git push origin master
}

ready

if   [ "$1" == "new"     ]; then new;
elif [ "$1" == "old"     ]; then old;
elif [ "$1" == "profile" ]; then profile;
elif [ -f "$Awk/$1.awk"  ]; then
  AWKPATH="$Awk:$AWKPATH" gawk          \
       --dump-variables=$Tmp/awkvars.out \
       --profile=$Tmp/awkprof.out         \
       -f $1.awk
  vars;
else 
	echo "usage ./aok (new | old | profile | file)"
fi 
