theme: jekyll-theme-minimal
highlighter: rogue
title: AOK is AWK plus objects
description: |
   Adds simple abstract data types to 
   AWK. Also offers nested data structures. 
   By Tim Menzies http://menzies.us
