theme: jekyll-theme-minimal
highlighter: rogue
twitter_username: timmenzies
github_username: timm
title: "AOK= AWK+objects"
description: "Adds (simple) abstract data types to AWK. Enables complex nesteted data structures."
